baseURL = "https://lucasfelz.github.io/lucasfelz-writeups/"
languageCode = "pt-br"
title = "Vuln-Hunter"
theme = "blowfish"

enableEmoji = true
enableRobotsTXT = true
paginate = 10
summaryLength = 30

[outputs]
  home = ["HTML", "RSS", "JSON"]

[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"

[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

[minify]
  disableXML = true
  minifyOutput = true
