languageCode = "en"
languageName = "English"
displayName = "EN"
isoCode = "en"
weight = 1
rtl = false
title = "CYBER KYUSHO"

[params]
  displayName = "EN"
  isoCode = "en"
  dateFormat = "2 January 2006"
  
  [params.author]
    name = "Lucas Felz"
    image = "https://avatars.githubusercontent.com/u/188224184"
    headline = "Finding Critical Points in Cyber Defense"
    bio = "Passionate about cybersecurity, pentesting and CTF write-ups."
    links = [
      { email = "mailto:lucasfelz@gmail.com" },
      { github = "https://github.com/lucasfelz" },
    ]
