[[main]]
  name = "Write-ups"
  pageRef = "writeups"
  weight = 10

[[main]]
  name = "Posts"
  pageRef = "posts"
  weight = 20

[[main]]
  name = "Tags"
  pageRef = "tags"
  weight = 30

[[main]]
  name = "Categorias"
  pageRef = "categories"
  weight = 40

[[main]]
  name = "Sobre"
  pageRef = "about"
  weight = 50

[[footer]]
  name = "Contato"
  pageRef = "about"
  weight = 10
