baseURL = "https://lucasfelz.github.io/"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Lucas Felz"


enableRobotsTXT = true

[languages]
  [languages.en]
    languageName = "English"
    weight = 1

    [languages.en.params]
      description = "Cybersecurity Portfolio | Infrastructure"
      rtl = false
      dateformat = "2006-01-02"

[module]
  [[module.imports]]
    path = "github.com/nunocoracao/blowfish"

